// export default {
// PORT: process.env.PORT ?? 3500,
// ATLAS_CONNECTION_STRING:process.env.ATLAS_CONNECTION_STRING
// };

export const envConfiguration ={
PORT:'PORT',
ATLAS_CONNECTION_STRING:'ATLAS_CONNECTION_STRING',
SALT:'SALT',
JWT_SECRET:'JWT_SECRET',
JWT_EXP:'JWT_EXP',
MONGO_URI:'MONGO_URI',
CLOUD_NAME:'CLOUD_NAME',
API_KEY:'API_KEY',
API_SECRET:'API_SECRET',
MAILGUN_PUBLIC_KEY:'MAILGUN_PUBLIC_KEY',
MAILGUN_PRIVATE_KEY:'MAILGUN_PRIVATE_KEY',
MAILGUN_WEBHOOK_KEY:'MAILGUN_WEBHOOK_KEY',
MAILGUN_DOMAIN_NAME:'MAILGUN_DOMAIN_NAME',
MAILGUN_FROM_EMAIL:'MAILGUN_FROM_EMAIL',
AWS_Access_Key_Id: "AWS_Access_Key_Id",
AWS_Secret_Key:"AWS_Secret_Key",
SENDGRID_API_KEY:'SENDGRID_API_KEY',
BUCKET_NAME: "BUCKET_NAME",
FLW_SECRET_KEY: "FLW_SECRET_KEY",
FLW_PUBLIC_KEY: 'FLW_PUBLIC_KEY',
}